import { describe, it, expect } from 'vitest';
import { sanitizeBlogHtml } from '@/lib/sanitize';

/**
 * R-03 — the sanitizer itself is a security control, so these tests assert on
 * the actual sanitized output: executable payloads must not survive, while the
 * editor's legitimate formatting must.
 */
describe('sanitizeBlogHtml (stored XSS)', () => {
  it('removes <script> payloads entirely', () => {
    const out = sanitizeBlogHtml('<p>hi</p><script>alert(1)</script>');
    expect(out).not.toContain('<script');
    expect(out).not.toContain('alert(1)');
    expect(out).toContain('<p>hi</p>');
  });

  it('removes event-handler attributes (onerror/onclick/onload)', () => {
    expect(sanitizeBlogHtml('<img src="x" onerror="alert(1)">')).not.toContain('onerror');
    expect(sanitizeBlogHtml('<div onclick="alert(1)">x</div>')).not.toContain('onclick');
    expect(sanitizeBlogHtml('<body onload="alert(1)">x</body>')).not.toContain('onload');
    expect(sanitizeBlogHtml('<svg onload="alert(1)"></svg>')).not.toContain('onload');
    for (const out of [
      sanitizeBlogHtml('<img src="x" onerror="alert(1)">'),
      sanitizeBlogHtml('<div onclick="alert(1)">x</div>'),
    ]) {
      expect(out).not.toContain('alert(1)');
    }
  });

  it('rejects javascript: URLs in href/src but keeps relative & http(s)', () => {
    expect(sanitizeBlogHtml('<a href="javascript:alert(1)">click</a>')).not.toContain('javascript:');
    expect(sanitizeBlogHtml('<a href="JaVaScRiPt:alert(1)">click</a>')).not.toContain('javascript:');
    expect(sanitizeBlogHtml('<img src="javascript:alert(1)">')).not.toContain('javascript:');
    // data:text/html and vbscript: are non-http protocols and never survive.
    expect(sanitizeBlogHtml('<a href="data:text/html,<script>alert(1)</script>">x</a>')).not.toContain('data:');
    expect(sanitizeBlogHtml('<a href="vbscript:msgbox(1)">x</a>')).not.toContain('vbscript:');

    const safe = sanitizeBlogHtml(
      '<a href="https://example.com">a</a><a href="/relative">b</a><img src="/uploads/x.png">',
    );
    expect(safe).toContain('href="https://example.com"');
    expect(safe).toContain('href="/relative"');
    expect(safe).toContain('src="/uploads/x.png"');
  });

  it('drops dangerous elements (iframe/svg/style/form) with their payloads', () => {
    const out = sanitizeBlogHtml(
      '<iframe src="https://evil.test"></iframe><svg><script>alert(1)</script></svg>' +
        '<style>*{background:url(javascript:alert(1))}</style><form action="x">y</form>',
    );
    expect(out).not.toContain('<iframe');
    expect(out).not.toContain('<svg');
    expect(out).not.toContain('<style');
    expect(out).not.toContain('<form');
    expect(out).not.toContain('alert(1)');
  });

  it('preserves legitimate rich text generated by the editor', () => {
    const legit =
      '<h2>Hello</h2><p><strong>Bold</strong> text</p><ul><li>Item</li></ul>' +
      '<a href="https://example.com">Safe link</a>';
    const out = sanitizeBlogHtml(legit);
    expect(out).toContain('<h2>Hello</h2>');
    expect(out).toContain('<strong>Bold</strong>');
    expect(out).toContain('<li>Item</li>');
    expect(out).toContain('href="https://example.com"');
    expect(out).toContain('Safe link');
  });

  it('keeps text-align styling but strips arbitrary CSS', () => {
    const aligned = sanitizeBlogHtml('<p style="text-align: center">mid</p>');
    expect(aligned).toContain('text-align: center');

    const css = sanitizeBlogHtml(
      '<p style="position:fixed;top:0;left:0;width:100%;z-index:99999">overlay</p>',
    );
    expect(css).not.toContain('position');
    expect(css).not.toContain('z-index');
  });

  it('never emits event handlers for mixed payloads', () => {
    const out = sanitizeBlogHtml(
      '<p onmouseover="alert(1)" style="text-align:left">t</p>' +
        '<a href="https://ok.test" onclick="alert(2)" target="_blank">l</a>',
    );
    expect(out).not.toMatch(/\son\w+?=/i);
    expect(out).not.toContain('alert');
    expect(out).toContain('href="https://ok.test"');
    expect(out).toMatch(/text-align:\s*left/);
  });

  it('returns an empty string for empty input', () => {
    expect(sanitizeBlogHtml('')).toBe('');
  });
});
